easy_admin:
    site_name: '<em style="font-size: 90%;">Opieka Nad Zwierzętami</em>'
#    list:
#        actions: ['searchData']
    design:
#        brand_color: 'rgba(245,245,245, 0.8)'
        color_scheme : 'light'
        menu:
            - { label: 'Dashboard', route: 'admin_dashboard', icon: 'desktop', default: true }
            - { label: 'Grafik', route: 'employees_shedule', icon: 'desktop'}
            - label: 'Raporty'
              icon: 'calendar'
              children:
                  - { entity: 'WorkTime', label: 'Godziny pracy', icon: 'address-card' }
                  - { entity: 'Raport', label: 'Raport', icon: 'envelope' }
                  - 'Status'
            - { entity: 'User', label: 'Użytkownicy', icon: 'user' }
            - label: 'Zwierzęta'
              icon: 'paw'
              children:
                - { entity: 'Animal', label: 'Zwierzęta', icon: 'paw' }
                - { entity: 'VisitDate', label: 'Wizyty', icon: 'book' }
    list:
        title: 'Lista: %%entity_label%%'
        actions:
            - { name: 'new', label: 'Nowy'}
            - { name: 'show', icon: 'info-circle', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }

    entities:
        Raport:
            class: AppBundle\Entity\Raport
            controller: AppBundle\Controller\EasyAdmin\RaportController
            list:
                fields:
                    - id
                    - { property: 'user', label: 'Opiekun' }
                    - { property: 'animal', label: 'Zwierzę' }
                    - { property: 'message', label: 'Raport' }
                    - { property: 'date', format: 'd-m-Y H:i', label: 'Wysłany' }
                actions: ['searchData']
        Status:
            class: AppBundle\Entity\Status
            label: Statusy
            list:
                fields:
                    - id
                    - status
        WorkTime:
            class: AppBundle\Entity\WorkTime
            controller: AppBundle\Controller\EasyAdmin\WorkTimeController
            label: Czas pracy
            list:
                fields:
                    - id
                    - { property: 'start', format: 'd-m-Y H:i', label: 'Start' }
                    - { property: 'end', format: 'd-m-Y H:i', label: 'Koniec' }
                    - { property: 'user', label: 'Opiekun' }
                    - { property: 'animal', label: 'Zwierzę' }
                    - status
                actions: ['searchData', 'raport']
        User:
            class: AppBundle\Entity\User
            controller: AppBundle\Controller\EasyAdmin\UserController
            label: Użytkownicy
            disabled_actions: ['show']
            list:
                fields:
                    - id
                    - { property: 'username', label: 'Imię i Nazwisko' }
                    - { property: 'email', type: 'email', label: 'Email' }
                    - { property: 'hourlyRateVisit', label: 'Spacer (zł/h)', type_options: { currency: 'PLN' } }
                    - { property: 'hourlyRateDrive', label: 'Dojazd (zł/h)', type_options: { currency: 'PLN' } }
                    - { property: 'enabled', label: 'Aktywny' }
                    - { property: 'lastLogin', format: 'H:i d-m-Y', label: 'Ostatnie logowanie' }
                actions: ['-show']
            edit:
                title: 'Edycja: %%entity_label%%'
                fields:
                    - { property: 'username', label: 'Imię i Nazwisko' }
                    - { property: 'email', type: 'email' }
                    - { property: 'hourlyRateVisit', type: 'money', label: 'Stawka spacer', type_options: { currency: 'PLN' } }
                    - { property: 'hourlyRateDrive', type: 'money', label: 'Stawka dojazd', type_options: { currency: 'PLN' } }
                    - { property: 'enabled', type: 'checkbox', label: 'Aktywny?' }
                    - { property: 'plainPassword', type_options: { required: false} }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Opiekun': 'ROLE_USER', 'Admin': 'ROLE_ADMIN' } } }
                form_options: { validation_groups: ['Profile'] }
            new:
                title: 'Nowy użytkownik'
                fields:
                    - { property: 'username', label: 'Imię i Nazwisko' }
                    - { property: 'email', type: 'email' }
                    - { property: 'hourlyRateVisit', type: 'money', label: 'Stawka spacer', type_options: { currency: 'PLN' } }
                    - { property: 'hourlyRateDrive', type: 'money', label: 'Stawka dojazd', type_options: { currency: 'PLN' } }
                    - { property: 'enabled', type: 'checkbox', label: 'Aktywny?' }
                    - { property: 'plainPassword', type: 'password', label: 'Hasło', type_options: { required: true} }
                    - { property: 'roles', label: 'Rodzaj', type: 'choice', type_options: { multiple: true, choices: { 'Opiekun': 'ROLE_USER', 'Admin': 'ROLE_ADMIN' } } }
                form_options: { validation_groups: ['Registration'] }
        Animal:
            class: AppBundle\Entity\Animal
            label: Zwierzęta
            form:
                title: 'Nowe zwierzątko'
                fields:
                    - { property: 'name', label: 'Imię' }
                    - { property: 'address', label: 'Adres', help: 'adres nr, miasto' }
                    - { property: 'hourlyRate', type: 'money', label: 'Stawka godzinowa', type_options: { currency: 'PLN' } }
                    - { property: 'description', type: 'ckeditor', label: 'Opis' }
                    - { property: 'playlistId', label: 'Id playlisty' }
                form_options: { validation_groups: ['Registration'] }
        VisitDate:
            class: AppBundle\Entity\VisitDate
            controller: AppBundle\Controller\EasyAdmin\VisitDateController
            label: Test
            form:
                fields:
                    - { property: 'begin', label: 'Od', type: date, type_options: { mapped: false, widget: 'single_text' } }
                    - { property: 'end', label: 'Do', type: date, type_options: { mapped: false, widget: 'single_text' } }
                    - { property: 'perDay', label: 'Ile dziennie', type: choice, type_options: {choices: { '1':'1', '2':'2', '3':'3', '4':'4'}, mapped: false, data: '1' } }
                    - animal
